version : '3.2'

services: 
  rabbitmq:
    image: "rabbitmq:3.8.17-management"
    environment: 
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "medical-pass"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: 
      - app_net

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/datadir:/var/lib/mysql
    ports:
        - "3306:3306"
    env_file: 
      - ./env/mysql.env
    networks: 
      - app_net
    depends_on: 
      - rabbitmq

  publisher_api:
    build: ./UserAntropometricsAPI
    ports: 
      - "8091:8081"
    networks: 
      - app_net
    depends_on: 
      - rabbitmq

  reciever_api:
    build: ./Industry4MedicalRecieverAPI
    env_file: 
      - ./env/mysql.env
    networks: 
      - app_net
    depends_on: 
      - mysql
    links: 
      - rabbitmq
    restart: on-failure

networks:
  app_net:
    driver: bridge